### ISSUE TITLE
[Bug] Remove duplicated contributions

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/sage-monorepo#2118] opened 2023-09-13 04:24 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What product(s) are you seeing the problem on?

OpenChallenges

### Current behavior

In the examples below, IBM and Mount Sinai are listed twice in lists of challenge contributors.

Task:

1. [ ] Check for duplicated contributions in OC Data (@vpchung )
2. [ ] Review frontend implementation (@rrchai )

<img width="1433" alt="Screen Shot 2023-09-09 at 6 30 56 AM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/dbaca719-338d-4f19-bc78-decde0e73dd2">

<img width="1435" alt="Screen Shot 2023-09-09 at 6 31 30 AM" src="https://github.com/Sage-Bionetworks/sage-monorepo/assets/3056480/262f5bce-5a36-42ab-8a0c-17fcb9cf4de9">

### Commit ID

770a5cc0958a66eb246729ea7f1dae0736c0befb

### Are you developing inside the dev container?

- [X] I am using the dev container

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vpchung** [comment] 2023-09-13 22:20
This is a duplicate of #1947

**Closed** 2023-09-13 22:24 UTC
Labels: bug
