### ISSUE TITLE
[Feature] Define Challenges, Organizations and Platforms

### ISSUE THREAD

**Issue by gaiaandreoletti** [Sage-Bionetworks/sage-monorepo#2180] opened 2023-09-29 00:36 UTC
### What product(s) is this feature for?

OpenChallenges

### Description

Would be great to have a glossary of definitions for some of the most used terms. Such as:

**Glossary**
**Challenge**: a call to take part in a contest or competition. Challenges are typically built on large and complex data sets, focused on scientifically impactful and timely research questions. They result in a set of solutions to the given problem, originating from groups and researchers all over the world.

**Benchmark**: systematic assessment of the performance of a variety of methods for a given task normally based on defined case studies and metrics.

**Platform**: any hardware or software used to host an application or service. (e.g. synapse, Drupal, etc.)

**Organization**: describe a research modality where diverse and independent researchers come together to focus on one or more limited sets of tasks. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tschaffter** [comment] 2023-09-29 01:48
Duplicate of #2171. Keeping the present ticket as it is more fleshed out.

**Comment by tschaffter** [comment] 2023-09-29 17:24
The proposed descriptions should be reviewed and accepted by the team before we could close this ticket.

**Comment by tschaffter** [comment] 2023-09-29 17:28
Let's track this work in #2171.

**Closed by tschaffter** 2023-09-29 17:28 UTC
Labels: documentation

**Comment by gaiaandreoletti** [comment] 2023-09-29 17:53
I closed this ticket because the feature was already described in another ticket with more detail, and I pasted the definitions there to avoid redundancy.
